name: Breman
favicon: null
layout_spectrum: 0.589599
typography_spectrum: 0.344086
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#b6dbeb'
    - '#424c57'
    - '#48679e'
    - '#9a3e13'
  brandStrength: 0.8546399
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.8884712
purpose: []
