layout_spectrum: 0.589599
name: Breman
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8546399
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.8884712
  brandColors:
    - '#020202'
    - '#CEC7BE'
    - '#7FB4BE'
    - '#F2FFFF'
    - '#4366CF'
typography_spectrum: 0.344086
